/* automatically generated by rust-bindgen 0.59.1 */

use cty;

extern "C" {
    pub fn foo_reset();
}
extern "C" {
    pub fn foo_get_value() -> cty::c_int;
}
extern "C" {
    pub fn foo_set_value(value: cty::c_int);
}
